#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator


@dataclass(frozen=True)
class ScanCategory:
    id: str
    name: str
    description: str
    path: str


@dataclass
class ChildItem:
    path: str
    size_bytes: int
    item_count: int
    is_whitelisted: bool
    matched_filter: bool


@dataclass
class CategoryResult:
    id: str
    name: str
    description: str
    root_path: str
    exists: bool
    file_count: int
    total_size_bytes: int
    child_items: list[ChildItem]
    warnings: list[str]


@dataclass
class ScanReport:
    scanned_at: str
    total_size_bytes: int
    total_files: int
    category_count: int
    app_filter: str | None
    whitelist: list[str]
    categories: list[CategoryResult]


@dataclass
class DeletionResult:
    deleted_paths: list[str]
    skipped_paths: list[str]
    errors: list[str]


CATEGORIES = [
    ScanCategory(
        id="user-caches",
        name="User Caches",
        description="Application caches under ~/Library/Caches",
        path="~/Library/Caches",
    ),
    ScanCategory(
        id="user-logs",
        name="User Logs",
        description="Diagnostic and application logs",
        path="~/Library/Logs",
    ),
    ScanCategory(
        id="trash",
        name="Trash",
        description="Files currently in the macOS Trash",
        path="~/.Trash",
    ),
    ScanCategory(
        id="xcode-derived-data",
        name="Xcode DerivedData",
        description="Build intermediates generated by Xcode",
        path="~/Library/Developer/Xcode/DerivedData",
    ),
    ScanCategory(
        id="xcode-archives",
        name="Xcode Archives",
        description="Archived app builds kept by Xcode",
        path="~/Library/Developer/Xcode/Archives",
    ),
    ScanCategory(
        id="ios-simulators",
        name="iOS Simulators",
        description="Simulator device data and app containers",
        path="~/Library/Developer/CoreSimulator/Devices",
    ),
    ScanCategory(
        id="mail-downloads",
        name="Mail Downloads",
        description="Temporary files from Apple Mail attachments",
        path="~/Library/Containers/com.apple.mail/Data/Library/Mail Downloads",
    ),
    ScanCategory(
        id="ios-backups",
        name="iPhone Backups",
        description="Finder or iTunes device backups",
        path="~/Library/Application Support/MobileSync/Backup",
    ),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scan and clean common junk-file locations on macOS."
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output the result as JSON.",
    )
    parser.add_argument(
        "--top",
        type=positive_int,
        default=5,
        help="Show the N largest first-level items in each category.",
    )
    parser.add_argument(
        "--include-missing",
        action="store_true",
        help="Include categories whose paths do not exist.",
    )
    parser.add_argument(
        "--app",
        help="Only keep items whose first-level name contains this app keyword.",
    )
    parser.add_argument(
        "--whitelist",
        action="append",
        default=[],
        help="Protect items matching this keyword or absolute path. Repeatable.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the displayed junk items after confirmation.",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the confirmation prompt when used with --clean.",
    )
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Launch a native Tk GUI.",
    )
    return parser.parse_args()


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def normalized_text(value: str | None) -> str | None:
    if value is None:
        return None
    stripped = value.strip()
    return stripped.casefold() if stripped else None


def normalize_whitelist(patterns: list[str]) -> list[str]:
    normalized: list[str] = []
    for pattern in patterns:
        cleaned = pattern.strip()
        if cleaned:
            normalized.append(cleaned)
    return normalized


def item_matches_filter(name: str, app_filter: str | None) -> bool:
    if not app_filter:
        return True
    return app_filter in name.casefold()


def item_is_whitelisted(item_path: Path, patterns: list[str]) -> bool:
    if not patterns:
        return False

    path_text = str(item_path)
    path_folded = path_text.casefold()
    name_folded = item_path.name.casefold()

    for pattern in patterns:
        expanded_pattern = str(Path(pattern).expanduser())
        folded_pattern = expanded_pattern.casefold()
        if os.path.isabs(expanded_pattern):
            try:
                if item_path.resolve(strict=False).is_relative_to(Path(expanded_pattern).resolve(strict=False)):
                    return True
            except OSError:
                if path_folded.startswith(folded_pattern):
                    return True
        else:
            if folded_pattern in name_folded or folded_pattern in path_folded:
                return True
    return False


def scan_categories(
    categories: list[ScanCategory],
    top: int,
    include_missing: bool,
    app_filter: str | None,
    whitelist: list[str],
) -> ScanReport:
    results: list[CategoryResult] = []

    for category in categories:
        result = scan_category(category, top, app_filter, whitelist)
        if include_missing or result.exists:
            if not app_filter or result.child_items or result.total_size_bytes > 0:
                results.append(result)

    results.sort(key=lambda item: item.total_size_bytes, reverse=True)

    return ScanReport(
        scanned_at=datetime.now(timezone.utc).isoformat(),
        total_size_bytes=sum(item.total_size_bytes for item in results),
        total_files=sum(item.file_count for item in results),
        category_count=len(results),
        app_filter=app_filter,
        whitelist=whitelist,
        categories=results,
    )


def scan_category(
    category: ScanCategory,
    top: int,
    app_filter: str | None,
    whitelist: list[str],
) -> CategoryResult:
    root = Path(category.path).expanduser()
    warnings: list[str] = []

    if not root.exists() or not root.is_dir():
        return CategoryResult(
            id=category.id,
            name=category.name,
            description=category.description,
            root_path=str(root),
            exists=False,
            file_count=0,
            total_size_bytes=0,
            child_items=[],
            warnings=["Path does not exist or is not a directory."],
        )

    total_size = 0
    file_count = 0
    top_level_sizes: dict[str, int] = {}
    top_level_counts: dict[str, int] = {}

    for item_path, item_size, item_warning in walk_files(root):
        if item_warning:
            warnings.append(item_warning)
            continue

        if item_path is None:
            continue

        relative_parts = item_path.relative_to(root).parts
        if not relative_parts:
            continue

        top_level_name = relative_parts[0]
        if not item_matches_filter(top_level_name, app_filter):
            continue

        total_size += item_size
        file_count += 1
        top_level_sizes[top_level_name] = top_level_sizes.get(top_level_name, 0) + item_size
        top_level_counts[top_level_name] = top_level_counts.get(top_level_name, 0) + 1

    child_items = [
        ChildItem(
            path=str(root / name),
            size_bytes=size,
            item_count=top_level_counts.get(name, 0),
            is_whitelisted=item_is_whitelisted(root / name, whitelist),
            matched_filter=item_matches_filter(name, app_filter),
        )
        for name, size in sorted(
            top_level_sizes.items(),
            key=lambda pair: (-pair[1], pair[0]),
        )[:top]
    ]

    return CategoryResult(
        id=category.id,
        name=category.name,
        description=category.description,
        root_path=str(root),
        exists=True,
        file_count=file_count,
        total_size_bytes=total_size,
        child_items=child_items,
        warnings=unique_keep_order(warnings),
    )


def walk_files(root: Path) -> Iterator[tuple[Path | None, int, str | None]]:
    stack = [root]

    while stack:
        current = stack.pop()

        try:
            with os.scandir(current) as entries:
                for entry in entries:
                    try:
                        if entry.is_symlink():
                            continue

                        if entry.is_dir(follow_symlinks=False):
                            stack.append(Path(entry.path))
                            continue

                        if entry.is_file(follow_symlinks=False):
                            stat_info = entry.stat(follow_symlinks=False)
                            yield Path(entry.path), stat_info.st_size, None
                    except PermissionError as exc:
                        yield None, 0, f"Cannot access {entry.path}: {exc.strerror or str(exc)}"
                    except OSError as exc:
                        yield None, 0, f"Cannot inspect {entry.path}: {exc.strerror or str(exc)}"
        except PermissionError as exc:
            yield None, 0, f"Cannot access {current}: {exc.strerror or str(exc)}"
        except OSError as exc:
            yield None, 0, f"Cannot inspect {current}: {exc.strerror or str(exc)}"


def unique_keep_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def format_bytes(size: int) -> str:
    units = ["B", "KB", "MB", "GB", "TB"]
    value = float(size)
    unit_index = 0

    while value >= 1024 and unit_index < len(units) - 1:
        value /= 1024
        unit_index += 1

    if unit_index == 0:
        return f"{int(value)} {units[unit_index]}"
    return f"{value:.1f} {units[unit_index]}"


def print_human_report(report: ScanReport) -> None:
    print("Mac Junk Scan")
    print(f"Scanned at: {report.scanned_at}")
    print(f"Categories: {report.category_count}")
    print(f"Files: {report.total_files}")
    print(f"Estimated junk size: {format_bytes(report.total_size_bytes)}")
    if report.app_filter:
        print(f"App filter: {report.app_filter}")
    if report.whitelist:
        print(f"Whitelist: {', '.join(report.whitelist)}")
    print("")

    for category in report.categories:
        print(f"[{category.name}] {format_bytes(category.total_size_bytes)}")
        print(category.description)
        print(f"Path: {category.root_path}")
        print(f"Files: {category.file_count}")

        if category.child_items:
            print("Top items:")
            for item in category.child_items:
                name = Path(item.path).name
                protection = " [whitelisted]" if item.is_whitelisted else ""
                print(
                    f"  - {name}: {format_bytes(item.size_bytes)} "
                    f"({item.item_count} files){protection}"
                )

        if category.warnings:
            print("Warnings:")
            for warning in category.warnings:
                print(f"  - {warning}")

        print("")


def json_default(value: object) -> object:
    if hasattr(value, "__dataclass_fields__"):
        return asdict(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def collect_deletion_targets(report: ScanReport) -> list[Path]:
    targets: list[Path] = []
    for category in report.categories:
        for item in category.child_items:
            if item.is_whitelisted:
                continue
            targets.append(Path(item.path))
    return targets


def confirm_deletion(targets: list[Path]) -> bool:
    if not targets:
        print("No deletable items were found after whitelist protection.")
        return False

    print("The following items will be deleted:")
    for target in targets:
        print(f"  - {target}")

    reply = input("Continue? [y/N]: ").strip().casefold()
    return reply in {"y", "yes"}


def delete_targets(targets: list[Path]) -> DeletionResult:
    deleted_paths: list[str] = []
    skipped_paths: list[str] = []
    errors: list[str] = []

    for target in targets:
        if not target.exists():
            skipped_paths.append(str(target))
            continue

        try:
            if target.is_dir():
                shutil.rmtree(target)
            else:
                target.unlink()
            deleted_paths.append(str(target))
        except OSError as exc:
            errors.append(f"Failed to delete {target}: {exc.strerror or str(exc)}")

    return DeletionResult(
        deleted_paths=deleted_paths,
        skipped_paths=skipped_paths,
        errors=errors,
    )


def print_deletion_result(result: DeletionResult) -> None:
    print("")
    print("Cleanup summary")
    print(f"Deleted: {len(result.deleted_paths)}")
    print(f"Skipped: {len(result.skipped_paths)}")
    print(f"Errors: {len(result.errors)}")

    if result.errors:
        print("Errors:")
        for error in result.errors:
            print(f"  - {error}")


def launch_gui() -> int:
    import tkinter as tk
    from tkinter import messagebox, ttk

    state: dict[str, object] = {
        "report": None,
        "targets": [],
    }

    root = tk.Tk()
    root.title("Mac Junk Scanner")
    root.geometry("980x680")
    root.minsize(840, 560)

    controls = ttk.Frame(root, padding=12)
    controls.pack(fill="x")

    ttk.Label(controls, text="App keyword").grid(row=0, column=0, sticky="w")
    app_var = tk.StringVar()
    app_entry = ttk.Entry(controls, textvariable=app_var, width=28)
    app_entry.grid(row=1, column=0, padx=(0, 12), sticky="ew")

    ttk.Label(controls, text="Whitelist").grid(row=0, column=1, sticky="w")
    whitelist_var = tk.StringVar()
    whitelist_entry = ttk.Entry(controls, textvariable=whitelist_var, width=40)
    whitelist_entry.grid(row=1, column=1, padx=(0, 12), sticky="ew")

    ttk.Label(controls, text="Top items").grid(row=0, column=2, sticky="w")
    top_var = tk.StringVar(value="5")
    top_spin = ttk.Spinbox(controls, from_=1, to=50, textvariable=top_var, width=6)
    top_spin.grid(row=1, column=2, padx=(0, 12), sticky="w")

    include_missing_var = tk.BooleanVar(value=False)
    include_missing = ttk.Checkbutton(
        controls,
        text="Include missing paths",
        variable=include_missing_var,
    )
    include_missing.grid(row=1, column=3, padx=(0, 12), sticky="w")

    controls.columnconfigure(0, weight=1)
    controls.columnconfigure(1, weight=2)

    button_row = ttk.Frame(root, padding=(12, 0, 12, 12))
    button_row.pack(fill="x")

    summary_var = tk.StringVar(value="Run a scan to view junk candidates.")
    summary_label = ttk.Label(button_row, textvariable=summary_var)
    summary_label.pack(side="left")

    tree_frame = ttk.Frame(root, padding=(12, 0, 12, 12))
    tree_frame.pack(fill="both", expand=True)

    columns = ("category", "item", "size", "files", "status", "path")
    tree = ttk.Treeview(tree_frame, columns=columns, show="headings")
    tree.heading("category", text="Category")
    tree.heading("item", text="Item")
    tree.heading("size", text="Size")
    tree.heading("files", text="Files")
    tree.heading("status", text="Status")
    tree.heading("path", text="Path")
    tree.column("category", width=140, anchor="w")
    tree.column("item", width=180, anchor="w")
    tree.column("size", width=110, anchor="e")
    tree.column("files", width=80, anchor="e")
    tree.column("status", width=110, anchor="center")
    tree.column("path", width=420, anchor="w")

    yscroll = ttk.Scrollbar(tree_frame, orient="vertical", command=tree.yview)
    xscroll = ttk.Scrollbar(tree_frame, orient="horizontal", command=tree.xview)
    tree.configure(yscrollcommand=yscroll.set, xscrollcommand=xscroll.set)
    tree.grid(row=0, column=0, sticky="nsew")
    yscroll.grid(row=0, column=1, sticky="ns")
    xscroll.grid(row=1, column=0, sticky="ew")
    tree_frame.columnconfigure(0, weight=1)
    tree_frame.rowconfigure(0, weight=1)

    def read_whitelist() -> list[str]:
        return normalize_whitelist(whitelist_var.get().split(","))

    def run_scan() -> None:
        try:
            top = positive_int(top_var.get())
        except Exception:
            messagebox.showerror("Invalid top value", "Top items must be a positive integer.")
            return

        report = scan_categories(
            CATEGORIES,
            top=top,
            include_missing=include_missing_var.get(),
            app_filter=normalized_text(app_var.get()),
            whitelist=read_whitelist(),
        )
        state["report"] = report
        state["targets"] = collect_deletion_targets(report)

        tree.delete(*tree.get_children())
        for category in report.categories:
            if not category.child_items:
                tree.insert(
                    "",
                    "end",
                    values=(
                        category.name,
                        "(no matching items)",
                        format_bytes(category.total_size_bytes),
                        category.file_count,
                        "info",
                        category.root_path,
                    ),
                )
                continue

            for item in category.child_items:
                tree.insert(
                    "",
                    "end",
                    values=(
                        category.name,
                        Path(item.path).name,
                        format_bytes(item.size_bytes),
                        item.item_count,
                        "whitelisted" if item.is_whitelisted else "candidate",
                        item.path,
                    ),
                )

        summary_var.set(
            f"{report.category_count} categories, {report.total_files} files, "
            f"{format_bytes(report.total_size_bytes)} candidate data"
        )

    def clean_displayed() -> None:
        report = state.get("report")
        if report is None:
            messagebox.showinfo("Nothing to clean", "Run a scan first.")
            return

        targets = collect_deletion_targets(report)
        if not targets:
            messagebox.showinfo(
                "Nothing to clean",
                "No deletable items were found after applying the whitelist.",
            )
            return

        preview = "\n".join(str(path) for path in targets[:12])
        extra = "" if len(targets) <= 12 else f"\n... and {len(targets) - 12} more"
        confirmed = messagebox.askyesno(
            "Confirm cleanup",
            "The following items will be deleted:\n\n"
            f"{preview}{extra}\n\nContinue?",
        )
        if not confirmed:
            return

        result = delete_targets(targets)
        if result.errors:
            messagebox.showwarning(
                "Cleanup finished with errors",
                f"Deleted {len(result.deleted_paths)} items.\n"
                f"Errors: {len(result.errors)}\n\n"
                + "\n".join(result.errors[:8]),
            )
        else:
            messagebox.showinfo(
                "Cleanup finished",
                f"Deleted {len(result.deleted_paths)} items successfully.",
            )
        run_scan()

    ttk.Button(button_row, text="Scan", command=run_scan).pack(side="right", padx=(8, 0))
    ttk.Button(button_row, text="Clean Displayed", command=clean_displayed).pack(
        side="right"
    )

    run_scan()
    app_entry.focus_set()
    root.mainloop()
    return 0


def main() -> int:
    args = parse_args()

    if args.gui:
        return launch_gui()

    app_filter = normalized_text(args.app)
    whitelist = normalize_whitelist(args.whitelist)
    report = scan_categories(
        CATEGORIES,
        top=args.top,
        include_missing=args.include_missing,
        app_filter=app_filter,
        whitelist=whitelist,
    )

    if args.json:
        print(json.dumps(report, default=json_default, ensure_ascii=False, indent=2))
    else:
        print_human_report(report)

    if not args.clean:
        return 0

    targets = collect_deletion_targets(report)
    if not args.yes and not confirm_deletion(targets):
        print("Cleanup cancelled.")
        return 0

    result = delete_targets(targets)
    print_deletion_result(result)
    return 0 if not result.errors else 1


if __name__ == "__main__":
    sys.exit(main())
